### ISSUE TITLE
How do I use this command in sudo

### ISSUE THREAD

**Issue by angadschawla** [laktak/rsyncy#7]
Hello, 

I installed this package using pip3 in sudo so that it installed for root user. I then use the command with sudo and get that the command is not found. How do I do this correctly?

Thanks!

**Comment by RemiZlatinis** [comment]
Do you mean with sudo? Like "sudo rsyncy -a ..."?

**Comment by angadschawla** [comment]
@RemiZlatinis That is right! I did figure out a workaround by just directly pointing to the Python file for execution in script. Not sure if you know of a better method...

**Comment by RemiZlatinis** [comment]
In my system, I install it regularly as a normal user. ('pip install rsyncy')
And it works just fine with the sudo prefix, both in terminal and scripts.
The command not found for python modules was probably caused by an invalid installation. And that usually happens if you install with pip running as root. 
In general, is bad practice to install packages with sudo. And I suggest you use environments.
